version: '3'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: iotbb/iot-bb-node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    command: "npm start"
    restart: always
