version: '3'
services:
  rails:
    container_name: iot-bb-rails
    build:
      context: ./rails
      dockerfile: Dockerfile
    image: iotbb/iot-bb-rails${TAG}
    working_dir: /usr/src/app
    command: "rails server"
    restart: always
  mongo:
    container_name: iot-bb-mongo
    image: mongo:4
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345789
    restart: always