version: '3'
services:
  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    image: iotbb/iot-bb-rails
    working_dir: /usr/src/app
    command: "rails server"
    restart: always
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345789
    restart: always